include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore


custom_lint:
  rules:
    # Explicitly disable one lint rule
    - missing_provider_scope: false
