name: changemaker_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  flutter_riverpod: ^3.0.0-dev.17
  auto_route: ^10.1.0+1
  injectable: ^2.5.1
  get_it: ^8.1.0
  google_fonts: ^6.3.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  auth_buttons: ^3.0.3
  snacknload: ^1.0.9
  google_sign_in: ^7.1.1
  form_validator: ^2.1.1
  cloud_firestore: ^6.0.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  onboarding: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  riverpod_lint: ^3.0.0-dev.17
  custom_lint: ^0.8.0
  build_runner: ^2.5.4
  auto_route_generator: ^10.1.0
  injectable_generator: ^2.7.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  slang_build_runner: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
