// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdorhPFwp4CpOhozmoRoxARc3cu4CVtDM',
    appId: '1:802072297266:android:b949d106045e46e068e12b',
    messagingSenderId: '802072297266',
    projectId: 'changemaker-22f3c',
    storageBucket: 'changemaker-22f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhymsYUMJTS-P51adj_0QS_5Fg-gDiazw',
    appId: '1:802072297266:ios:d0199c2ae18b396468e12b',
    messagingSenderId: '802072297266',
    projectId: 'changemaker-22f3c',
    storageBucket: 'changemaker-22f3c.firebasestorage.app',
    androidClientId: '802072297266-ebieotkuiqboitu3t9lbg6omt11gaelh.apps.googleusercontent.com',
    iosClientId: '802072297266-81ppprf27tnjm5pqno0914mumbl8l6mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.changemakerFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOwTyNRavMTaVxeM0OAxjqQNLnptGobY',
    appId: '1:802072297266:web:032b25dc4ad6455568e12b',
    messagingSenderId: '802072297266',
    projectId: 'changemaker-22f3c',
    authDomain: 'changemaker-22f3c.firebaseapp.com',
    storageBucket: 'changemaker-22f3c.firebasestorage.app',
    measurementId: 'G-3VLXZEFPHS',
  );

}